### ISSUE TITLE
I randomly hit a CUDA error when running your code

### ISSUE THREAD

**Issue by ifed-ucsd** [VITA-Group/TEGNAS#19]
The error is:

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Strangely, if I simply restart the search, I am able to process networks for which previously I hit the CUDA error. 

Is there some sort of garbage collection that is missing?

**Comment by chenwydj** [comment]
Bug fixed: error was due to 0 gradients in some bad architectures.
